import type { Metadata } from "next";
import "./globals.css";
import "react-image-gallery/styles/css/image-gallery.css";
import "react-alice-carousel/lib/alice-carousel.css";
import Header from "./Header";
import { arabic_font } from "@/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={`${arabic_font.className} `}>
      <body className="mx-auto flex min-h-screen max-w-[375px] flex-col items-center overflow-x-hidden py-6">
        <Header />
        {children}
      </body>
    </html>
  );
}
