export const services = [
  {
    id: 1,
    name: "منكير كلاسيك",
    categories: ["العناية بالأظافر"],
    price: 100,
    oldPrice: 150,
    description: "منكير كلاسيك لتحسين مظهر الأظافر وإضافة لون جميل.",
    discountActive: true,
    active: true,
    order: 1,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "08:00", to: "20:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "ساعة واحدة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 2,
    name: "لون عادي",
    categories: ["العناية بالأظافر"],
    price: 50,
    oldPrice: 80,
    description: "لون عادي للأظافر لإضفاء لمسة نهائية أنيقة.",
    discountActive: true,
    active: false,
    order: 2,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "30 دقيقة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 3,
    name: "بديكير",
    categories: ["العناية بالأظافر"],
    price: 150,
    oldPrice: 200,
    description: "بديكير للعناية بالقدمين وتنعيم البشرة.",
    discountActive: true,
    active: true,
    order: 3,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "ساعة واحدة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 4,
    name: "علاج القدم",
    categories: ["العناية بالأظافر"],
    price: 120,
    oldPrice: 180,
    description: "علاج القدم للتخلص من الجلد الميت وتنعيم البشرة.",
    discountActive: true,
    active: true,
    order: 4,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "45 دقيقة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 5,
    name: "قص الشعر",
    categories: ["العناية بالشعر"],
    price: 200,
    oldPrice: 300,
    description: "قص الشعر لتحسين مظهر الشعر وإضفاء تسريحة جديدة.",
    discountActive: true,
    active: true,
    order: 5,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "ساعة واحدة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 6,
    name: "تصفيف الشعر",
    categories: ["العناية بالشعر"],
    price: 150,
    oldPrice: 250,
    description: "تصفيف الشعر لإعطاء مظهر نهائي أنيق وجذاب.",
    discountActive: true,
    active: true,
    order: 6,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "45 دقيقة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 7,
    name: "تنظيف الوجه",
    categories: ["العناية بالبشرة"],
    price: 250,
    oldPrice: 400,
    description: "تنظيف الوجه لإزالة الشوائب والبثور وتحسين نضارة البشرة.",
    discountActive: true,
    active: true,
    order: 7,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "ساعة واحدة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 8,
    name: "ماسك",
    categories: ["العناية بالبشرة"],
    price: 100,
    oldPrice: 150,
    description: "ماسك للوجه لترطيب وتغذية البشرة.",
    discountActive: true,
    active: true,
    order: 8,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "30 دقيقة",
    minimumDaysBeforeReservation: 1,
  },
  {
    id: 9,
    name: "تلوين شعر",
    categories: ["العناية بالشعر"],
    price: 300,
    oldPrice: 500,
    description: "تلوين شعر باستخدام أحدث تقنيات الصبغ للحصول على لون مثالي.",
    discountActive: true,
    active: true,
    order: 9,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "ساعتين",
    minimumDaysBeforeReservation: 2,
  },
  {
    id: 10,
    name: "علاج الكيراتين",
    categories: ["العناية بالشعر"],
    price: 500,
    oldPrice: 800,
    description: "علاج الكيراتين لتنعيم الشعر وإصلاح التلف.",
    discountActive: true,
    active: true,
    order: 10,
    images: ["https://via.placeholder.com/150", "https://via.placeholder.com/150"],
    practitioners: ["Practitioner 1", "Practitioner 2"],
    days: {
      Monday: { from: "09:00", to: "18:00" },
      Tuesday: { from: "09:00", to: "18:00" },
      Wednesday: { from: "09:00", to: "18:00" },
      Thursday: { from: "09:00", to: "18:00" },
      Friday: { from: "09:00", to: "18:00" },
      Saturday: null,
      Sunday: null,
    },
    duration: "3 ساعات",
    minimumDaysBeforeReservation: 2,
  }
];
